[process1]
inputs.var_name1 = ""
inputs.var_name2 = ""
fcn = "path/to/file:fcn_name"
subset = "subset1"

[process1.outputs]
var_name1 = "var1"
var_name2 = "var2"

[process2]
inputs.var_name1 = "process1.var1" # Can be any Process in this package.
fcn = "path/to/file:fcn_name"
subset = "subset2"
outputs.var_name1 = "var1"