site_name: ResearchOS
site_author: Mitchell Tillman
repo_name: ResearchOS
repo_url: https://github.com/ResearchOS/ResearchOS
site_url: https://researchos.github.io/ResearchOS/
theme:
  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.top

plugins:
  - search  
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_signature: true
            show_docstrings: true
          selection:
            members: true
            docstring_style: "google"
          options:
            filters:
              - "!^__.*__$"
              - "!^_"
              - "!^validate"
              - "!^to_json"
              - "!^from_json"
              - "!^load_"
              - "!^save_"

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - admonition

nav:
  - Home: Home/index.md
  - Developer:
    - Overview: Developer/index.md
    - Packages:
      - Overview: Developer/Package_Setup/index.md
      - Discovery: Developer/Package_Setup/discovery.md
    - DAG:
      - Overview: Developer/DAG/index.md
    - Compilation:
      - Overview: Developer/Compilation/index.md
      - Connectivity: Developer/Compilation/connectivity.md
      - Running: Developer/Compilation/running.md
    - Running:
      - Overview: Developer/Running/index.md
      - Selecting Runnables: Developer/Running/selecting_runnables.md
      - Running a Runnable: Developer/Running/running_runnables.md
      - Uniqely Identifying Nodes: Developer/Running/unique_identifiers.md
    - Bridges:
      - Overview: Developer/Bridges/index.md
      - Bridges.toml: Developer/Bridges/bridges_toml.md
    - Nodes:
      - Overview: Developer/Nodes/index.md
      - Runnables: 
        - Overview: Developer/Nodes/Runnables/index.md
        - Process: Developer/Nodes/Runnables/process.md
        - Plot: Developer/Nodes/Runnables/plot.md
        - Stats: Developer/Nodes/Runnables/stats.md
        - Logsheet: Developer/Nodes/Runnables/logsheet.md
      - Variables:
        - Overview: Developer/Nodes/Variables/index.md
        - Input Variables: 
          - Overview: Developer/Nodes/Variables/Input Variables/index.md
          - Unspecified: Developer/Nodes/Variables/Input Variables/unspecified.md
          - Dynamic: Developer/Nodes/Variables/Input Variables/dynamic.md
          - Hard-Coded: Developer/Nodes/Variables/Input Variables/hard_coded.md
        - Output Variables: Developer/Nodes/Variables/output_variables.md