site_name: ResearchOS
site_author: Mitchell Tillman
repo_name: ResearchOS
repo_url: https://github.com/ResearchOS/ResearchOS
theme:
  name: material
  features:
    - navigation.path

plugins:
  - search
  - mkdocstrings:
      default_handler: python
