site_name: ResearchOS
site_author: Mitchell Tillman
repo_name: ResearchOS
repo_url: https://github.com/ResearchOS/ResearchOS
site_url: https://researchos.github.io/ResearchOS/
theme:
  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.top

plugins:
  - search  
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_signature: true
            show_docstrings: true
          selection:
            members: true
            docstring_style: "google"
          options:
            filters:
              - "!^__.*__$"
              - "!^_"
              - "!^validate"
              - "!^to_json"
              - "!^from_json"
              - "!^load_"
              - "!^save_"

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - admonition

nav:
  - Home: Home/index.md
  - Developer:
    - Overview: Developer/index.md
    - Packages:
      - Overview: Developer/Package_Setup/index.md
      - Discovery: Developer/Package_Setup/discovery.md
    - Compilation:
      - Overview: Developer/Compilation/index.md
      - Connectivity: Developer/Compilation/connectivity.md
      - Running: Developer/Compilation/running.md
    - Running:
      - Overview: Developer/Running/index.md
      - Selecting Runnables: Developer/Running/selecting_runnables.md
      - Running a Runnable: Developer/Running/running_runnables.md