[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/.venv",
  "/docs",
  "/how_to",
  "mkdocs.yml",
  "/research_objects",
  "requirements_dev.txt",
  "pypi_upload_instructions.md",
  "dev_env_file.py",
  "researchos.db",
  "researchos_data.db",
  "Spr23TWW_OA_AllSubjects_032323_TEST.csv",
  "Spr23TWW_OA_AllSubjects_032323.xlsx",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ResearchOS"]

[project]
name = "ResearchOS"
version = "0.0.13"
requires-python = ">=3.7"
authors = [
    {name = "Mitchell Tillman <mtillman14@gmail.com>"},
]
description = "Operating system for scientific research."
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Natural Language :: English", 
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent"
]
# Runtime dependencies
# pycparser, PyGithub, and requests are from requirements.txt found here: https://github.com/Nordgaren/Github-Folder-Downloader/blob/master/requirements.txt
dependencies = [
  "networkx>=3.2.1",
  "numpy>=1.26.4",
  "pycparser==2.21",
  "PyGithub==1.57",
  "requests==2.28.2",
  "typer==0.11.1",  
<<<<<<< HEAD
  "toml>=0.10.2"
=======
  "toml>=0.10.2",
  "matplotlib==3.8.4",
  "netgraph==4.13.2",
  "scipy==1.13.1"
>>>>>>> code-sharing-test-MT2
]

[project.optional-dependencies]
# Development dependencies
dev = [
  "pytest>=8.0.1",
  "mkdocstrings==0.24.0",
  "mkdocs-material==9.5.10",
  "mkdocstrings-python==1.8.0",
<<<<<<< HEAD
  "netgraph>=4.13.2",
=======
>>>>>>> code-sharing-test-MT2
  "snakeviz>=2.2.0"
]

[project.urls]
Documentation = "https://researchos.github.io/ResearchOS/"
Repository = "https://github.com/ResearchOS/ResearchOS"

[project.scripts]
<<<<<<< HEAD
ros = "ResearchOS.cli_entrypoint:app"
=======
ros = "ResearchOS.cli_entrypoint:app"
pl = "ResearchOS.cli_pl_entrypoint:app"

# [tool.researchos]
# index = "src/index.toml"
>>>>>>> code-sharing-test-MT2
