name: Deploy AutoMKDocs

on:
  push:
    branches:
      = main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
            - run: pip install -r requirements_dev.txt
            - run: pip test
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt
            - name: Lint with Ruff
              run: |
                pip install ruff
                ruff check .
              continue-on-error: true
            - name: Deploy mkdocs
              run: |
                git config --global user.email "mtillman14@gmail.com"
                git config --global user.name "mtillman14"
                git fetch origin gh-pages
                git rebase origin/gh-pages
                git push origin gh-pages
                mkdocs gh-deploy
            - name: Test with pytest
              run: |
                coverage run -m pytest -v -s
            - name: Generate Coverage Report
              run: |
                    coverage report -m