[fake_process1]
batch = "Trial"
outputs = ["y1", "y2"]
inputs.x1 = "?"
path = "src/ResearchOS/ros-fake/processes/fake_processes.py::fake_process1"
subset = "subset1"

[fake_process2]
batch = "Trial"
outputs = ["y1", "y2"]
inputs.x1 = "fake_process1.y1"
inputs.x2 = "fake_process1.y2"
path = "src/ResearchOS/ros-fake/processes/fake_processes.py::fake_process2"
subset = "subset1"