on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Coveralls GitHub Action"
        uses: coverallsapp/github-action@v2.2.3
        # other configuration options here...
